<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test_Login_Data_Binding</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5a4a4eda-96d2-4992-82d0-462d8a9e4136</testSuiteGuid>
   <testCaseLink>
      <guid>d8e2fe63-3937-419d-af56-e140926c9491</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NEW_TC/Login_Datra_Binding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3fb673d9-283b-48bc-8003-2174e0158d82</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3fb673d9-283b-48bc-8003-2174e0158d82</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>5b812b85-cf58-4b1d-b258-d54b1baee777</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fb673d9-283b-48bc-8003-2174e0158d82</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>a4905568-7157-4c90-90d1-ba617a869346</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
